kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ./sales-pod/kind-sales-config.yaml
- ../base/sales-pod
- ./database-pod/postgres.yaml
patchesStrategicMerge:
- ./sales-pod/kind-sales-patch.yaml
images:
- name: sales-api-image # tells kustomize to search for this image name in spec.template.spec.cotainers and overwrite it 
  newName: sales-api-amd64 
  newTag: "v1.0.0" # default tag, it would be overwritten by kustomize edit command 

