kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ./sales-pod/kind-sales-config.yaml
- ../base/sales-pod
- ./database-pod/postgres.yaml
patchesStrategicMerge:
- ./sales-pod/kind-sales-patch.yaml
images:
- name: sales-api-image
  newName: sales-api-amd64
  newTag: v1.1.1
